# Import's & Dataloaders

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Create a base directory (relative path)
data_dir = Path("Data")

marketData = pd.read_csv(data_dir / "city_market_tracker.tsv000", sep="\t")

# Skiprows for not reading the reader of the files

Crime2024 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2024.csv", skiprows=5)
Crime2023 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2023.csv", skiprows=5)
Crime2022 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2022.csv", skiprows=5)
Crime2021 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2021.csv", skiprows=5)
Crime2020 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2020.csv", skiprows=5)
Crime2019 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2019.csv", skiprows=5)
Crime2018 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2018.csv", skiprows=5)
Crime2017 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2017.csv", skiprows=5)
Crime2016 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2016.csv", skiprows=5)
Crime2015 = pd.read_csv(data_dir / "Number of Crimes by Offense Type_2015.csv", skiprows=5)

# Preprocessing:
### Market Data:

In [2]:
# take the merketData and drop some columns to reduce size
columns=[]
marketData = marketData.drop(columns)

# drop all data where 'STATE' is not 'Massachusetts'
marketData = marketData[marketData['STATE'] == 'Massachusetts']

In [3]:
# Ensure PERIOD_BEGIN is datetime and create year column
marketData['PERIOD_BEGIN'] = pd.to_datetime(marketData['PERIOD_BEGIN'], errors='coerce')
marketData['year'] = marketData['PERIOD_BEGIN'].dt.year

### Crime Data:

In [4]:
Crime = [Crime2024, 
         Crime2023, 
         Crime2022, 
         Crime2021, 
         Crime2020, 
         Crime2019, 
         Crime2018, 
         Crime2017,
         Crime2016,
         Crime2015]

Year = [2024,
        2023,
        2022,
        2021,
        2020,
        2019,
        2018,
        2017,
        2016,
        2015]

for i in range(len(Crime)):
    Crime[i]['Year'] = Year[i]

Crime_combined = pd.concat(Crime, ignore_index=True)

display(Crime_combined[Crime_combined['Offense Type']=='Barnstable'])

# rename Crime_combined 'Offense Type' to 'City'

Crime_combined = Crime_combined.rename(columns={'Offense Type': 'City'})

display(Crime_combined[Crime_combined['City']=='Barnstable'])

,Offense Type,All Offense Types,Crimes Against Person,Murder and Nonnegligent Manslaughter,Negligent Manslaughter,Justifiable Homicide,Kidnapping/Abduction,All Rape,Rape,Sodomy,...,Sports Tampering,Pornography/Obscene Material,Prostitution,Assisting or Promoting Prostitution,Purchasing Prostitution,Weapon Law Violations,Animal Cruelty,Missing,Unnamed: 59,Year
1,Barnstable,"1,634",614,1.0,NaN,NaN,10.0,34.0,29.0,1.0,...,NaN,13.0,1.0,NaN,9.0,35.0,NaN,NaN,NaN,2024
507,Barnstable,"1,722",631,NaN,NaN,NaN,3.0,29.0,20.0,7.0,...,NaN,13.0,NaN,NaN,2.0,37.0,3.0,NaN,NaN,2023
1012,Barnstable,"1,749",708,1.0,1.0,NaN,13.0,26.0,21.0,4.0,...,NaN,9.0,NaN,1.0,1.0,45.0,2.0,NaN,NaN,2022
1517,Barnstable,"1,639",679,1.0,1.0,NaN,8.0,32.0,21.0,6.0,...,NaN,7.0,1.0,NaN,NaN,34.0,4.0,NaN,NaN,2021
2022,Barnstable,"1,831",612,NaN,NaN,NaN,5.0,31.0,18.0,7.0,...,NaN,6.0,NaN,NaN,NaN,28.0,NaN,NaN,NaN,2020
2527,Barnstable,"1,607",635,2.0,1.0,NaN,5.0,23.0,15.0,6.0,...,NaN,6.0,NaN,NaN,NaN,22.0,2.0,NaN,NaN,2019
3032,Barnstable,"1,639",575,2.0,NaN,NaN,4.0,20.0,12.0,6.0,...,NaN,8.0,NaN,NaN,1.0,50.0,1.0,NaN,NaN,2018
3537,Barnstable,"1,926",641,1.0,NaN,NaN,2.0,18.0,13.0,4.0,...,NaN,7.0,2.0,NaN,8.0,45.0,1.0,NaN,NaN,2017
4042,Barnstable,"2,252",684,1.0,NaN,NaN,5.0,16.0,16.0,NaN,...,NaN,7.0,3.0,NaN,NaN,46.0,NaN,NaN,NaN,2016
4547,Barnstable,"2,494",759,2.0,NaN,NaN,13.0,22.0,22.0,NaN,...,NaN,9.0,1.0,NaN,NaN,55.0,NaN,NaN,NaN,2015

,City,All Offense Types,Crimes Against Person,Murder and Nonnegligent Manslaughter,Negligent Manslaughter,Justifiable Homicide,Kidnapping/Abduction,All Rape,Rape,Sodomy,...,Sports Tampering,Pornography/Obscene Material,Prostitution,Assisting or Promoting Prostitution,Purchasing Prostitution,Weapon Law Violations,Animal Cruelty,Missing,Unnamed: 59,Year
1,Barnstable,"1,634",614,1.0,NaN,NaN,10.0,34.0,29.0,1.0,...,NaN,13.0,1.0,NaN,9.0,35.0,NaN,NaN,NaN,2024
507,Barnstable,"1,722",631,NaN,NaN,NaN,3.0,29.0,20.0,7.0,...,NaN,13.0,NaN,NaN,2.0,37.0,3.0,NaN,NaN,2023
1012,Barnstable,"1,749",708,1.0,1.0,NaN,13.0,26.0,21.0,4.0,...,NaN,9.0,NaN,1.0,1.0,45.0,2.0,NaN,NaN,2022
1517,Barnstable,"1,639",679,1.0,1.0,NaN,8.0,32.0,21.0,6.0,...,NaN,7.0,1.0,NaN,NaN,34.0,4.0,NaN,NaN,2021
2022,Barnstable,"1,831",612,NaN,NaN,NaN,5.0,31.0,18.0,7.0,...,NaN,6.0,NaN,NaN,NaN,28.0,NaN,NaN,NaN,2020
2527,Barnstable,"1,607",635,2.0,1.0,NaN,5.0,23.0,15.0,6.0,...,NaN,6.0,NaN,NaN,NaN,22.0,2.0,NaN,NaN,2019
3032,Barnstable,"1,639",575,2.0,NaN,NaN,4.0,20.0,12.0,6.0,...,NaN,8.0,NaN,NaN,1.0,50.0,1.0,NaN,NaN,2018
3537,Barnstable,"1,926",641,1.0,NaN,NaN,2.0,18.0,13.0,4.0,...,NaN,7.0,2.0,NaN,8.0,45.0,1.0,NaN,NaN,2017
4042,Barnstable,"2,252",684,1.0,NaN,NaN,5.0,16.0,16.0,NaN,...,NaN,7.0,3.0,NaN,NaN,46.0,NaN,NaN,NaN,2016
4547,Barnstable,"2,494",759,2.0,NaN,NaN,13.0,22.0,22.0,NaN,...,NaN,9.0,1.0,NaN,NaN,55.0,NaN,NaN,NaN,2015

# David Arzumanyan

In [5]:
display(Crime_combined.columns)

Index(['City', 'All Offense Types', 'Crimes Against Person',
       'Murder and Nonnegligent Manslaughter', 'Negligent Manslaughter',
       'Justifiable Homicide', 'Kidnapping/Abduction', 'All Rape', 'Rape',
       'Sodomy', 'Sexual Assault With An Object', 'Criminal Sexual Contact',
       'Incest', 'Statutory Rape', 'Aggravated Assault', 'Simple Assault',
       'Intimidation', 'Human Trafficking, Commercial Sex Acts',
       'Human Trafficking, Involuntary Servitude', 'Crimes Against Property',
       'Arson', 'Bribery', 'Burglary/Breaking & Entering',
       'Counterfeiting/Forgery', 'Destruction/Damage/Vandalism of Property',
       'Embezzlement', 'Extortion/Blackmail',
       'False Pretenses/Swindle/Confidence Game',
       'Credit Card/Automatic Teller Fraud', 'Impersonation', 'Welfare Fraud',
       'Wire Fraud', 'Identity Theft', 'Hacking/Computer Invasion', 'Robbery',
       'Pocket-picking', 'Purse-snatching', 'Shoplifting',
       'Theft From Building', 'Theft From Coin Operated Machine or Device',
       'Theft From Motor Vehicle', 'Theft of Motor Vehicle Parts/Accessories',
       'All Other Larceny', 'Motor Vehicle Theft', 'Stolen Property Offenses',
       'Crimes Against Society', 'Drug/Narcotic Violations',
       'Drug Equipment Violations', 'Betting/Wagering',
       'Operating/Promoting/Assisting Gambling',
       'Gambling Equipment Violations', 'Sports Tampering',
       'Pornography/Obscene Material', 'Prostitution',
       'Assisting or Promoting Prostitution', 'Purchasing Prostitution',
       'Weapon Law Violations', 'Animal Cruelty', 'Missing', 'Unnamed: 59',
       'Year'],
      dtype='object')

# Joe Tivnan

In [6]:
# create a function that takes a city name, crime, and year and plots a time series of the crime in that city for that year

def plot_crime_time_series(city, crime, year):
    # select only the 'Larceny' data for the given city and year and shape it for plotting
    if crime in Crime_combined.columns:
        subset = Crime_combined[(Crime_combined['City'] == city)].copy()
        data = subset[crime]
    else: return -1

    # plot the time series
    plt.figure(figsize=(10, 6))
    plt.plot(data['Year'], data[crime], marker='o')
    plt.title(f'Time Series of {crime} in {city} for {year}')
    plt.xlabel('Month')
    plt.ylabel('Number of Offenses')
    plt.grid()
    plt.show()

plot_crime_time_series('Boston', 'Arson', 2022)

KeyError: 'Year'

In [ ]:
display(marketData['AVG_SALE_TO_LIST'])

# plot a scatter plot in seaborn of AVG_SALE_TO_LIST vs DATE, using YYYY-MM-DD format for the BEGIN_PERIOD column
import seaborn as sns
import matplotlib.pyplot as plt

# Convert the 'BEGIN_PERIOD' column to datetime format
marketData['PERIOD_BEGIN'] = pd.to_datetime(marketData['PERIOD_BEGIN'])

# Create the scatter plot
plt.figure(figsize=(12, 6))
sns.scatterplot(data=marketData, x='PERIOD_BEGIN', y='AVG_SALE_TO_LIST')
plt.title('Average Sale to List Ratio Over Time')
plt.xlabel('Date')
plt.ylabel('Average Sale to List Ratio')
plt.xticks(rotation=45)
plt.tight_layout()

# add a mean line to the scatter plot and add a legend
mean_value = marketData['AVG_SALE_TO_LIST'].mean()
plt.axhline(mean_value, color='red', linestyle='--', label='Mean')
plt.legend()
plt.show()

# plot just the values from 2020
marketData_2020 = marketData[marketData['PERIOD_BEGIN'].dt.year == 2020]
plt.figure(figsize=(12, 6))
sns.scatterplot(data=marketData_2020, x='PERIOD_BEGIN', y='AVG_SALE_TO_LIST')
plt.title('Average Sale to List Ratio in 2020')
plt.xlabel('Date')
plt.ylabel('Average Sale to List Ratio')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# create a violin plot of all the distributions for 2020 by month
marketData_2020['MONTH'] = marketData_2020['PERIOD_BEGIN'].dt.month
plt.figure(figsize=(12, 6))
sns.violinplot(data=marketData_2020, x='MONTH', y='AVG_SALE_TO_LIST')
plt.title('Distribution of Average Sale to List Ratio by Month in 2020')
plt.xlabel('Month')
plt.ylabel('Average Sale to List Ratio')
plt.tight_layout()
plt.show()

In [ ]:
# Scatter plot of AVG_SALE_TO_LIST colored by year
import matplotlib.pyplot as plt
import seaborn as sns

# Ensure PERIOD_BEGIN is datetime and create year column
marketData['PERIOD_BEGIN'] = pd.to_datetime(marketData['PERIOD_BEGIN'], errors='coerce')
marketData['year'] = marketData['PERIOD_BEGIN'].dt.year

# Drop rows with missing year or missing AVG_SALE_TO_LIST
plot_df = marketData.dropna(subset=['year', 'AVG_SALE_TO_LIST']).copy()
plot_df['year'] = plot_df['year'].astype(int)

# Use a discrete palette for years present
years = sorted(plot_df['year'].unique())
palette = sns.color_palette('tab10', n_colors=len(years))

plt.figure(figsize=(12,6))
# To keep the scatter from being too dense, set alpha and edgecolor
sns.scatterplot(data=plot_df, x='PERIOD_BEGIN', y='AVG_SALE_TO_LIST', hue='year', palette=palette, legend='full', s=25, alpha=0.7)
plt.title('AVG_SALE_TO_LIST Over Time (colored by Year)')
plt.xlabel('Date')
plt.ylabel('Average Sale to List Ratio')
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend(title='Year', bbox_to_anchor=(1.01, 1), loc='upper left')
plt.show()

# Patrick Keufack

In [ ]:
print("Hello World!")

# Victor

In [ ]:
# Check Data

print("Rows and Columns:", Crime2024.shape)
print("\nColumns:", Crime2024.columns.tolist())
print("\nData Types:")
print(Crime2024.dtypes)
print("\nPreview:")
print(Crime2024.head())